# Site Info
title: RetroReversing
tagline: 'Retro Reversing'
description: 'Retro Video Game Reverse Engineering.'
baseurl: ""
url: https://www.retroreversing.com
logo: '/public/logo.png'
highlighter: rouge
rouge:
  theme: monokai

# Site configurations
plugins:
  - jekyll-redirect-from
  - jekyll-include-cache
  # - jekyll-paginate
# - jekyll-sitemap ( replaced with our own implementation)
whitelist:
  - jekyll-redirect-from
  - jekyll-include-cache

markdown: kramdown
kramdown:
  input: GFM # GitHub Flavored Markdown
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: false
    theme: monokai
    css_class: highlight

# To manually control the end of the excerpt uncomment:
# excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
permalink: pretty
incremental: true

exclude:
  - _site.backup
  - templates
  - node_modules
  - tmp
  - .cache
  - .DS_Store
  - scripts
  - .github
  - .git
  - .vscode

version: 1.0.0

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'

# Where are tags and categories displayed
# tag_page: '/blog/tags/'
# category_page: '/blog/categories/'

# hero:
#   image: /public/img/we_will_be_giants_by_yalestewart.jpg
#   caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>


# Plugins
mathjax: true # whether support mathjax
# google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'retro-reversing' # leave blank if you don't want disqus

category:
  "360":
    title: Microsoft Xbox 360
    image: /public/consoles/Microsoft Xbox 360.png
  "32x":
    title: Sega 32X
    image: /public/consoles/Sega 32X.png
  "3d":
    title: 3D
    image: /public/consoles/3d.png
  "3do":
    title: Panasonic 3DO
    image: /public/consoles/Panasonic 3DO.png
  "3ds":
    title: Nintendo 3DS
    image: /public/consoles/Nintendo 3DS.png
  "amiga":
    title: Amiga
    image: /public/consoles/Amiga.png
  "amstrad_cpc":
    title: Amstrad CPC
    image: /public/consoles/Amstrad CPC.png
  "android":
    title: Android
    image: /public/consoles/Android.png
  "arcade":
    title: Arcade
    image: /public/consoles/Arcade.png
  "bookazines":
    title: Bookazines
    image: /public/consoles/Magazine.png
  "cheatcartridge":
    title: Cheat Cartridge
    image: /public/consoles/Hardware.png
  "codemasters":
    title: Codemasters
    image: /public/consoles/PC.png
  "colecovision":
    title: Colecovision
    image: /public/consoles/Colecovision.png
  "cracking":
    title: Cracking
    image: /public/consoles/PC.png
  "crossproducts":
    title: Cross Products
    image: /public/consoles/Magazine.png
  "datel":
    title: Datel
    image: /public/consoles/PC.png
  "devkit":
    title: Development Hardware
    image: /public/consoles/Hardware.png
  "disassemblers":
    title: Disassemblers
    image: /public/consoles/PC.png
  "dos":
    title: DOS
    image: /public/consoles/PC.png
  "dreamcast":
    title: Sega Dreamcast
    image: /public/consoles/Sega Dreamcast.png
  "ds":
    title: Nintendo DS
    image: /public/consoles/Nintendo DS.png
  "fairchild-channel-f":
    title: Fairchild Channel F
    image: /public/consoles/Fairchild Channel F.png
  "famicom_disk_system":
    title: Nintendo Famicom Disk System
    image: /public/consoles/Nintendo Famicom Disk System.png
  "famicon":
    title: Nintendo Famicon
    image: /public/consoles/Nintendo Famicon.png
  "fileformats":
    title: File Formats
    image: /public/consoles/PC.png
  "gameboy":
    title: Nintendo Game Boy
    image: /public/consoles/Nintendo Game Boy.png
  "gamecom":
    title: Game.com
    image: /public/consoles/GameCom.png
  "gamecube":
    title: Nintendo Gamecube
    image: /public/consoles/Nintendo Gamecube.png
  "gameengines":
    title: Game Engines
    image: /public/consoles/PC.png
  "gamegear":
    title: Sega Game Gear
    image: /public/consoles/Sega Game Gear.png
  "games":
    title: Games
    image: /public/images/RetroReversingLogoSmall.png
  "gba":
    title: Nintendo Game Boy Advance
    image: /public/consoles/Nintendo Game Boy Advance.png
  "gbc":
    title: Nintendo Game Boy Color
    image: /public/consoles/Nintendo Game Boy Color.png
  "genesis":
    title: Sega Genesis
    image: /public/consoles/Sega Genesis.png
  "ghidra":
    title: Ghidra
    image: /public/consoles/PC.png
  "handhelds":
    title: Handhelds
    image: /public/consoles/Handhelds.png
  "hardware":
    title: Hardware
    image: /public/consoles/Hardware.png
  "incomplete":
    title: Incomplete
    image: /public/images/RetroReversingLogoSmall.png
  "industry":
    title: Industry
    image: /public/consoles/Magazine.png
  "intellivision":
    title: Intellivision
    image: /public/consoles/Intellivision.png
  "introduction":
    title: Introduction
    image: /public/consoles/PC.png
  "jaguar":
    title: Atari Jaguar
    image: /public/consoles/Atari Jaguar.png
  "atari":
    title: Atari
    image: /public/consoles/Atari 2600.png
  "leak":
    title: Leak
    image: /public/consoles/Leaks.png
  "lynx":
    title: Atari Lynx
    image: /public/consoles/Atari Lynx.png
  "magazines":
    title: Magazines
    image: /public/consoles/Magazine.png
  "mastersystem":
    title: Sega Master System
    image: /public/consoles/Sega - Master System.png
  "maths":
    title: Maths
    image: /public/consoles/PC.png
  "megadrive":
    title: Sega MegaDrive
    image: /public/consoles/Sega Megadrive.png
  "msx":
    title: MSX
    image: /public/consoles/PC.png
  "n64":
    title: Nintendo 64
    image: /public/consoles/Nintendo 64.png
  "pcengine":
    title: NEC PC Engine
    image: /public/consoles/Nec PC Engine.png
  "pcfx":
    title: NEC PC FX
    image: /public/consoles/Nec PC FX.png
  "neogeo":
    title: SNK Neo-Geo
    image: /public/consoles/SNK Neo-Geo.png
  "nes":
    title: Nintendo Entertainment System
    image: /public/consoles/Nintendo Entertainment System.png
  "news":
    title: News
    image: /public/consoles/Magazine.png
  "pc-88":
    title: PC-88
    image: /public/consoles/PC.png
  "pc":
    title: PC
    image: /public/consoles/PC.png
  "philips_cdi":
    title: Philips CD-i
    image: /public/consoles/Philips CD-i.png
  "pinball":
    title: Pinball
    image: /public/consoles/Pinball.png
  "pokemonmini":
    title: Pokemon Mini
    image: /public/consoles/PokemonMini.png
  "programming":
    title: Programming
    image: /public/consoles/PC.png
  "ps1":
    title: Sony Playstation
    image: /public/consoles/Sony Playstation.png
  "ps2":
    title: Sony PlayStation 2
    image: /public/consoles/Sony PlayStation 2.png
  "ps3":
    title: Sony Playstation 3
    image: /public/consoles/Sony Playstation 3.png
  "ps4":
    title: Sony Playstation 4
    image: /public/consoles/Sony Playstation 4.png
  "psp":
    title: PSP
    image: /public/consoles/psp.svg
  "satellaview":
    title: Nintendo Satellaview
    image: /public/consoles/Nintendo Satellaview.png
  "saturn":
    title: Sega Saturn
    image: /public/consoles/Sega Saturn.png
  "sdk":
    title: SDK
    image: /public/consoles/SDK.png
  "segacd":
    title: SEGA CD
    image: /public/consoles/SEGA CD.png
  "sg1000":
    title: Sega SG-1000
    image: /public/consoles/Sega SG-1000.png
  "snes":
    title: Super Nintendo
    image: /public/consoles/SNES-USA.png
  "snsystems":
    title: SN Systems
    image: /public/consoles/Magazine.png
  "sourcecode":
    title: Source Code
    image: /public/consoles/SourceCode.png
  "switch":
    title: Nintendo Switch
    image: /public/consoles/Nintendo Switch.png
  "symbols":
    title: Symbols
    image: /public/consoles/PC.png
  "tools":
    title: Tools
    image: /public/consoles/PC.png
  "turbografx16":
    title: TurboGrafx-16
    image: /public/consoles/TurboGrafx-16.png
  "tutorial":
    title: Tutorial
    image: /public/consoles/PC.png
  "vectrex":
    title: GCE Vectrex
    image: /public/consoles/GCE Vectrex.png
  "virtualboy":
    title: Nintendo Virtual Boy
    image: /public/consoles/Nintendo Virtual Boy.png
  "vita":
    title: Vita
    image: /public/consoles/Vita.png
  "wii":
    title: Nintendo Wii
    image: /public/consoles/Nintendo Wii.png
  "wiiu":
    title: Nintendo WiiU
    image: /public/consoles/Nintendo WiiU.png
  "wonderswan":
    title: WonderSwan
    image: /public/consoles/WonderSwan.png
  "xbox":
    title: Microsoft Xbox
    image: /public/consoles/Microsoft Xbox.png
  "xbox360":
    title: Microsoft Xbox 360
    image: /public/consoles/Microsoft Xbox 360.png
  "zxspectrum":
    title: Sinclair ZX Spectrum
    image: /public/consoles/Sinclair ZX Spectrum.png


references:
  - title: Behind The Screens
    name: BehindTheScreens
    link: https://www.youtube.com/channel/UC1scN415hiatrUSAg_51xqA
    image: https://yt3.ggpht.com/-59MNhf4K7fw/AAAAAAAAAAI/AAAAAAAAAAA/jA_EjpcyXIg/s288-c-k-no-mo-rj-c0xffffff/photo.jpg
  - title: Game Hut
    name: gamehut
    link: https://www.youtube.com/channel/UCfVFSjHQ57zyxajhhRc7i0g
    image: https://yt3.ggpht.com/a-/AN66SAzmSs3uEl8n6m0SWGpoACUDlukDsGtK_uPV4w=s288-mo-c-c0xffffffff-rj-k-no
  - title: YouTube
    name: youtube
    link: https://www.youtube.com/
    image: /public/Web-Youtube-alt-2-Metro-icon.png
  - title: Wayback Machine
    name: wayback
    link: https://archive.org/web/
    image: /public/references/wayback.jpg
  - title: Archive.org
    name: archive.org
    link: https://archive.org/
    image: /public/references/wayback.jpg
  - title: Devs Play (Double Fine)
    name: DevsPlay
    link: https://www.youtube.com/user/DoubleFineProd/
    image: /public/Web-Youtube-alt-2-Metro-icon.png
  - title: Computerphile
    name: computerphile
    link: https://www.youtube.com/channel/UC9-y-6csu5WGm29I7JiwpnA
    image: https://yt3.ggpht.com/-JFhbdoLwRlI/AAAAAAAAAAI/AAAAAAAAAAA/RemIzWPj2ZA/s288-c-k-no-mo-rj-c0xffffff/photo.jpg
  - title: ASSEMblergames.com
    name: assemblergames
    link: https://www.ASSEMblergames.com
    image: /public/references/assemblergames.png
  - title: Kim Justice
    name: kimjustice
    link: https://www.youtube.com/channel/UC9ZWVL1Elyt2cdiQYjxS_1w
    image: https://yt3.ggpht.com/-ns-hCUvw_1E/AAAAAAAAAAI/AAAAAAAAAAA/hPwWZRtfU1E/s88-c-k-no-mo-rj-c0xffffff/photo.jpg
  - title: SegaRetro.org
    name: segaretro.org
    link: https://www.segaretro.org
    image: https://segaretro.org/skins/foreground/assets/img/segaretro_logo.png

