# Site Info
title: RetroReversing
tagline: 'Retro Reversing'
description: 'Retro Video Game Reverse Engineering.'
baseurl: ""
url: https://www.retroreversing.com
logo: '/public/logo.png'
highlighter: rouge
rouge:
  theme: monokai

# Site configurations
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
# - jekyll-sitemap ( replaced with our own implementation)
whitelist:
  - jekyll-redirect-from

markdown: kramdown
kramdown:
  input: GFM # GitHub Flavored Markdown
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: false
    theme: monokai
    css_class: highlight

# To manually control the end of the excerpt uncomment:
# excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
# paginate: 5
# paginate_path: '/blog/page:num'
permalink: pretty
incremental: true

version: 1.0.0

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'

# Where are tags and categories displayed
# tag_page: '/blog/tags/'
# category_page: '/blog/categories/'

hero:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>


# Plugins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'retro-reversing' # leave blank if you don't want disqus

category_images:
  "360": /public/consoles/Microsoft Xbox 360.png
  32x: /public/consoles/Sega 32X.png
  3d: /public/consoles/3d.png
  3do: /public/consoles/Panasonic 3DO.png
  3ds: /public/consoles/Nintendo 3DS.png
  amiga: /public/consoles/Amiga.png
  amstrad_cpc: /public/consoles/Amstrad CPC.png
  android: /public/consoles/Android.png
  arcade: /public/consoles/Arcade.png
  atari_2600: /public/consoles/Atari 2600.png
  atari_5200: /public/consoles/Atari 5200.png
  atari_7800: /public/consoles/Atari 7800.png
  atari_800: /public/consoles/Atari 800.png
  atari_st: /public/consoles/Atari ST.png
  atari2600: /public/consoles/Atari 2600.png
  atarijaguar: /public/consoles/Atari Jaguar.png
  bookazines: /public/consoles/Magazine.png
  cheatcartridge: /public/consoles/Hardware.png
  codemasters: /public/consoles/PC.png
  colecovision: /public/consoles/Colecovision.png
  commodore_64: /public/consoles/Commodore 64.png
  commodore_amiga_cd32: /public/consoles/Commodore Amiga CD32.png
  commodore_cdtv: /public/consoles/Commodore CDTV.png
  computer_modern: /public/consoles/Computer Modern.png
  computer_old_design: /public/consoles/PC.png
  cracking: /public/consoles/PC.png
  crossproducts: /public/consoles/Magazine.png
  datel: /public/consoles/PC.png
  devkit: /public/consoles/Hardware.png
  disassemblers: /public/consoles/PC.png
  dos: /public/consoles/PC.png
  dreamcast: /public/consoles/Sega Dreamcast.png
  ds: /public/consoles/Nintendo DS.png
  fairchild-channel-f: /public/consoles/Fairchild Channel F.png
  famicom_disk_system: /public/consoles/Nintendo Famicom Disk System.png
  famicon: /public/consoles/Nintendo Famicon.png
  fileformats: /public/consoles/PC.png
  gameboy: /public/consoles/Nintendo Game Boy.png
  gamecom: /public/consoles/Game.com.png
  gamecube: /public/consoles/Nintendo Gamecube.png
  gameengines: /public/consoles/PC.png
  gamegear: /public/consoles/Sega Game Gear.png
  games: /public/images/RetroReversingLogoSmall.png
  gba: /public/consoles/Nintendo Game Boy Advance.png
  gbc: /public/consoles/Nintendo Game Boy Color.png
  genesis: /public/consoles/Sega Genesis.png
  ghidra: /public/consoles/PC.png
  handhelds: /public/consoles/Handhelds.png
  hardware: /public/consoles/Hardware.png
  incomplete: /public/images/RetroReversingLogoSmall.png
  industry: /public/consoles/Magazine.png
  intellivision: /public/consoles/Intellivision.png
  introduction: /public/consoles/PC.png
  jaguar: /public/consoles/Atari Jaguar.png
  leak: /public/consoles/Leaks.png
  lynx: /public/consoles/Atari Lynx.png
  magazines: /public/consoles/Magazine.png
  magnavox_odyssey_2: /public/consoles/Magnavox Odyssey 2.png
  magnavox_odyssey: /public/consoles/Magnavox Odyssey.png
  mastersystem: /public/consoles/Sega - Master System.png
  matell_intellivision: /public/consoles/Matell Intellivision.png
  maths: /public/consoles/PC.png
  megadrive: /public/consoles/Sega Megadrive.png
  msx: /public/consoles/PC.png
  n64: /public/consoles/Nintendo 64.png
  nds: /public/consoles/Nintendo DS.png
  nec_pc_engine_cd: /public/consoles/Nec PC Engine CD.png
  nec_pc_engine: /public/consoles/Nec PC Engine.png
  nec_pc_fx: /public/consoles/Nec PC FX.png
  nec_turbografx16_cd: /public/consoles/Nec TurboGrafx16 CD.png
  neogeo: /public/consoles/SNK Neo-Geo.png
  nes: /public/consoles/Nintendo Entertainment System.png
  news: /public/consoles/Magazine.png
  pc_engine_supergrafx: /public/consoles/PC Engine SuperGrafx.png
  pc-88: /public/consoles/PC.png
  pc: /public/consoles/PC.png
  philips_cdi: /public/consoles/Philips CD-i.png
  pinball: /public/consoles/Pinball.png
  pokemonmini: /public/consoles/PokemonMini.png
  PokemonMini: /public/consoles/PokemonMini.png
  programming: /public/consoles/PC.png
  ps1: /public/consoles/Sony Playstation.png
  ps2: /public/consoles/Sony PlayStation 2.png
  ps3: /public/consoles/Sony Playstation 3.png
  ps4: /public/consoles/Sony Playstation 4.png
  psp: /public/consoles/psp.svg
  satellaview: /public/consoles/Nintendo Satellaview.png
  saturn: /public/consoles/Sega Saturn.png
  sdk: /public/consoles/PC.png
  sega_mark_iii: /public/consoles/Sega Mark lll.png
  sega_sc3000: /public/consoles/Sega SC-3000.png
  segacd: /public/consoles/SEGA CD.png
  sg1000: /public/consoles/Sega SG-1000.png
  sinclair_zx_spectrum: /public/consoles/Sinclair ZX Spectrum.png
  snes: /public/consoles/SNES-USA.png
  snk_neo_geo_cd: /public/consoles/SNK Neo-Geo CD.png
  snk_neo_geo_pocket_color: /public/consoles/SNK Neo Geo Pocket Color.png
  snk_neo_geo_pocket: /public/consoles/SNK Neo Geo Pocket.png
  snsystems: /public/consoles/Magazine.png
  sony_playstation_2: /public/consoles/Sony PlayStation 2.png
  sony_playstation_3: /public/consoles/Sony Playstation 3.png
  sony_playstation: /public/consoles/Sony Playstation.png
  sony_psvita: /public/consoles/Sony PSVita.png
  sourcecode: /public/consoles/PC.png
  super_nintendo_entertainment_system: /public/consoles/Super Nintendo Entertainment System.png
  switch: /public/consoles/Nintendo Switch.png
  symbols: /public/consoles/PC.png
  tools: /public/consoles/PC.png
  turbografx16: /public/consoles/TurboGrafx-16.png
  tutorial: /public/consoles/PC.png
  vectrex: /public/consoles/GCE Vectrex.png
  virtualboy: /public/consoles/Nintendo Virtual Boy.png
  vita: /public/consoles/Vita.png
  wii: /public/consoles/Nintendo Wii.png
  wiiu: /public/consoles/Nintendo WiiU.png
  wonderswan_color: /public/consoles/WonderSwan Color.png
  wonderswan: /public/consoles/WonderSwan.png
  xbox: /public/consoles/Microsoft Xbox.png
  xbox360: /public/consoles/Microsoft Xbox 360.png
  zxspectrum: /public/consoles/Sinclair ZX Spectrum.png


references:
  - title: Behind The Screens
    name: BehindTheScreens
    link: https://www.youtube.com/channel/UC1scN415hiatrUSAg_51xqA
    image: https://yt3.ggpht.com/-59MNhf4K7fw/AAAAAAAAAAI/AAAAAAAAAAA/jA_EjpcyXIg/s288-c-k-no-mo-rj-c0xffffff/photo.jpg
  - title: Game Hut
    name: gamehut
    link: https://www.youtube.com/channel/UCfVFSjHQ57zyxajhhRc7i0g
    image: https://yt3.ggpht.com/a-/AN66SAzmSs3uEl8n6m0SWGpoACUDlukDsGtK_uPV4w=s288-mo-c-c0xffffffff-rj-k-no
  - title: YouTube
    name: youtube
    link: https://www.youtube.com/
    image: /public/Web-Youtube-alt-2-Metro-icon.png
  - title: Wayback Machine
    name: wayback
    link: https://archive.org/web/
    image: /public/references/wayback.jpg
  - title: Archive.org
    name: archive.org
    link: https://archive.org/
    image: /public/references/wayback.jpg
  - title: Devs Play (Double Fine)
    name: DevsPlay
    link: https://www.youtube.com/user/DoubleFineProd/
    image: /public/Web-Youtube-alt-2-Metro-icon.png
  - title: Computerphile
    name: computerphile
    link: https://www.youtube.com/channel/UC9-y-6csu5WGm29I7JiwpnA
    image: https://yt3.ggpht.com/-JFhbdoLwRlI/AAAAAAAAAAI/AAAAAAAAAAA/RemIzWPj2ZA/s288-c-k-no-mo-rj-c0xffffff/photo.jpg
  - title: ASSEMblergames.com
    name: assemblergames
    link: https://www.ASSEMblergames.com
    image: /public/references/assemblergames.png
  - title: Kim Justice
    name: kimjustice
    link: https://www.youtube.com/channel/UC9ZWVL1Elyt2cdiQYjxS_1w
    image: https://yt3.ggpht.com/-ns-hCUvw_1E/AAAAAAAAAAI/AAAAAAAAAAA/hPwWZRtfU1E/s88-c-k-no-mo-rj-c0xffffff/photo.jpg
  - title: SegaRetro.org
    name: segaretro.org
    link: https://www.segaretro.org
    image: https://segaretro.org/skins/foreground/assets/img/segaretro_logo.png

